static_resources:
  listeners:
    - name: listener_port_80
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 80

      filter_chains:
        - filters:
            - name: filter_http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: filter_http_connection_manager
                access_log:
                  - name: access_log_stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: router
                  virtual_hosts:
                    - name: virtual_host_all
                      domains:
                        - "*"
                      routes:
                        - name: redirect_http_to_https
                          match:
                            prefix: /
                          redirect:
                            https_redirect: true

    - name: listener_port_443
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 443

      filter_chains:
        - filters:
            - name: filter_http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: filter_http_connection_manager
                access_log:
                  - name: access_log_stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: router
                  virtual_hosts:
                    - name: virtual_host_www_site_local
                      domains:
                        - www.site.local
                      routes:
                        - name: route_to_cluster_www_site_local
                          match:
                            prefix: /
                          route:
                            cluster: cluster_www_site_local

                    - name: virtual_host_accounts_site_local
                      domains:
                        - accounts.site.local
                      routes:
                        - name: route_to_cluster_accounts_site_local
                          match:
                            prefix: /
                          route:
                            cluster: cluster_accounts_site_local

                    - name: virtual_host_api_site_local
                      domains:
                        - api.site.local
                      routes:
                        - name: route_to_cluster_api_site_local
                          match:
                            prefix: /
                          route:
                            cluster: cluster_api_site_local

                    - name: virtual_host_site_local
                      domains:
                        - site.local
                      routes:
                        - name: redirect_to_www_site_local
                          match:
                            prefix: /
                          redirect:
                            host_redirect: www.site.local

          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                alpn_protocols:
                  - h2,http/1.1
                tls_params:
                  tls_minimum_protocol_version: TLSv1_3
                tls_certificates:
                  - certificate_chain:
                      # certificate must valid for "site.local" and "*.site.local"
                      filename: cert.pem
                    private_key:
                      filename: key.pem

  clusters:
    - name: cluster_www_site_local
      connect_timeout: 1s
      type: STATIC
      load_assignment:
        cluster_name: www_site_local
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 3000

    - name: cluster_accounts_site_local
      connect_timeout: 5s
      load_assignment:
        cluster_name: accounts_site_local
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 4433

    - name: cluster_api_site_local
      connect_timeout: 5s
      load_assignment:
        cluster_name: api_site_local
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 4000
